### ISSUE TITLE
Default DEEPaaS bind address

### ISSUE THREAD

**Issue by Stifo** [indigo-dc/DEEPaaS#13]
When 127.0.0.1 is used as the default bind address, the docker container running DEEPaaS cannot be accessed on published port (-p 5000:5000). If this address is changed to 0.0.0.0 it works ok.

https://github.com/indigo-dc/DEEPaaS/blob/0c0cadd67b5dab5d4e7966463efb881575ec558b/deepaas/cmd/run.py#L29

**Comment by alvarolopez** [comment]
This is on purpose, we do not want to listen on `0.0.0.0` unless specified by the user
